---
title: "Exercise 4"
output: html_notebook
---


## Section 0

1.
```{r}
## install.packages("ggrepel")

library(ggplot2)
library(data.table)
library(magrittr)
library(tidyr)
library(ggrepel)
```

## Section 1

1.

## Section 2

1.
```{r}
?ggplot

data(mpg)
str(mpg)
mpg <- as.data.table(mpg)
str(mpg)
unique(mpg$year)

?geom_point
?geom_smooth

ggplot(mpg, aes(cty, hwy, color = factor(year))) + geom_point() + geom_smooth(method = 'lm')
```




## Section 3

1.
```{r}
data(iris)
iris_dt <- as.data.table(iris)
iris_dt
str(iris_dt)
```

2.
```{r}
?melt
iris_dt

iris_melt <- melt(iris_dt,id.vars = "Species")
iris_melt

?ggplot
?facet_wrap
ggplot(iris_melt, aes(value, color = Species)) + geom_histogram() + facet_wrap(iris_melt$variable)
```

3.
```{r}
?geom_histogram
?`~`
iris_melt

iris_melt %>% ggplot(aes(value, color = Species)) + geom_histogram(bins = 115)+facet_wrap(~variable)

```


4.
```{r}
ggplot(iris_melt, aes(variable, value))+ geom_boxplot()

```

5.
```{r}
?geom_jitter
?geom_boxplot

p <- ggplot(iris_melt,aes(variable, value))+geom_boxplot(outlier.shape = NA)


p + geom_jitter(width = 0.3, size = .5)

?geom_dotplot
p + geom_dotplot(binaxis = "y", stackdir="center", dotsize = .3)
```

6.
```{r}
?geom_violin
p <- ggplot(iris_melt,aes(variable, value))
p + geom_violin() + geom_boxplot(width=.03)
```

7.
```{r}
?geom_dotplot
p <- ggplot(iris_melt,aes(variable, value, color = Species))
p+ geom_dotplot(binaxis = "y", stackdir = "centerwhole", dotsize = .3)
```

## Section 4

1.
```{r}

p <- ggplot(iris_melt,aes(variable, value, color = Species))
p + geom_point()
```

2.
```{r}

p <- ggplot(iris_melt,aes(variable, value, color = Species))
p+ geom_point() + labs(x = "Petal Length", y = "Petal Width", title = "Relationship between petal length and width")+ theme(plot.title= element_text(hjust =.5))

?facet_wrap
p <- ggplot(iris_melt,aes(variable, value))
p + geom_point() + facet_wrap(~Species, scales = "free")

```

## Section 5

1.
```{r}
medals_dt <- fread("extdata/medals.csv")
str(medals_dt)

p<- ggplot(medals_dt, aes(total,population, color = country))
p + geom_point()
```

2.
```{r}
p<- ggplot(medals_dt, aes(total,population))
p+ geom_point()+ scale_x_log10()+ scale_y_log10()
```

3.
```{r}
?geom_text
p<- ggplot(medals_dt, aes(total,population))
p+ geom_point()+ scale_x_log10()+ scale_y_log10() + geom_text(aes(label = code))

library(ggrepel)

?geom_text_repel
p+ geom_point()+ scale_x_log10()+ scale_y_log10() + geom_text_repel(aes(label=code))
```


## Section 6

1.
```{r}
anscombe

anscombe_reshaped <- anscombe %>% as.data.table() %>%.[, ID := seq(nrow(.))] %>% melt(id.var=c("ID")) %>%separate(variable,c("xy", "group"), sep=1) %>% dcast(... ~ xy) %>%.[, group := paste0("dataset_", group)]

```

2.

3.

4.

5.
```{r}
boxplots_dt <- fread("extdata/boxplots.csv")
melt(boxplots_dt) %>% ggplot(aes(variable, value)) + geom_boxplot()
```

6.
```{r}
 melt(boxplots_dt) %>% ggplot(aes(variable, value)) + geom_violin()
```


## Section 7

1.
```{r}
mtcars <- data.table(mtcars)
str(mtcars)
ggplot(mtcars, aes(factor(cyl), mpg)) + geom_boxplot()


## First compute median
mtcars[, medians := median(mpg), by = cyl] ## Quantiles
mtcars[, c("lq", "uq") := .(quantile(mpg, 0.25), quantile(mpg, 0.75)), by = cyl]
## Whiskers
mtcars[, IQR := 1.5 * IQR(mpg), by = cyl]
mtcars[, c("up_IQR", "down_IQR") := .(IQR + uq, lq - IQR)]
## Get the most extreme value within 1.5*IQR
mtcars[mpg < up_IQR, up_whisker := max(mpg),by = "cyl"]
mtcars[mpg > down_IQR,down_whisker := min(mpg), by = "cyl"]
## Compute outliers
mtcars[, outlier := (mpg < down_IQR | mpg > up_IQR), by = "cyl"]
## Make the plot
ggplot(mtcars, aes(cyl, medians, ymax = uq, ymin = lq)) + geom_crossbar(fill = "white", width = 1.3) +geom_segment(aes(cyl, down_whisker, xend = cyl, yend = lq)) + geom_segment(aes(cyl, uq, xend = cyl, yend = up_whisker)) + geom_point(data = mtcars[outlier == TRUE], aes(cyl, mpg)) + labs(y = "mpg")
```






















