---
title: "Exercise 3"
output: html_notebook
---

## Section 00

```{r}
library(data.table)
library(magrittr)
library(tidyr)

```

## Section 01

1.

```{r}
str(AirPassengers)
AirPassengers
```
2.
```{r}

ChickWeight
```

3.

4.
```{r}
?read.csv
product_dt <- fread("extdata/example_product_data.csv")
str(product_dt)
product_dt
```

5.
```{r}
?melt
product_dt
product_dt[,Total:= producta+productb]

long_dt<-melt(product_dt,id.vars = "name")
long_dt<-melt(product_dt,id.vars = "name",variable.name = "product", value.name = "quantity")
long_dt
```

6.
```{r}
?dcast
?...
long_dt
str(long_dt)

wide_dt <- dcast(long_dt, ... ~ product, value.var = "quantity")
wide_dt
```

## Section 2

```{r}
mtcars_dt <- as.data.table(mtcars)
mtcars_dt[, carname := rownames(mtcars)]

dt1 <- mtcars_dt[5:25,.(carname, mpg, cyl)]
dt2<- mtcars_dt[1:10, .(carname, gear)]
```

1.
```{r}
?merge
str(dt1)
str(dt2)

inner_mg <- merge(dt1,dt2,by = "carname")
str(inner_mg)
```

2.
```{r}
left_mg<- merge(dt1, dt2, by = "carname", all.x = TRUE)
str(left_mg)
left_mg
```

3.
```{r}

outer_mg<- merge(dt1, dt2, by = "carname", all= T)
outer_mg[, .N]
```


## Section 3

1.
```{r}
messy_dt <- fread("extdata/weather.txt")
str(messy_dt)
messy_dt
```

2.

3.

4.
```{r}
## wide -> long
?melt
messy_dt
tidy_dt <- melt(messy_dt,id.vars = c("id", "year", "month", "element"), variable.name = "day", value.name = "temp")
tidy_dt[, day:= as.integer(gsub("d","",day))]
?paste
tidy_dt[, date:= paste(year, month, day, sep="-")]
tidy_dt[, c("year", "month", "day") := NULL]
tidy_dt
?tolower
tidy_dt[, element:= tolower(element)]
tidy_dt
tidy_dt <- dcast(tidy_dt, ... ~ element, value.var = "temp" ) 
tidy_dt
tidy_dt <- tidy_dt[!(is.na(tmax) & is.na(tmin)) ]


tidy_dt
```


## Section 4

1.
```{r}
?list.files

files <- list.files("extdata/baby-names", full.names =T)
files
str(files)
fread(files[23])
```

2.
```{r}
?basename
names(files) <- basename(files)
str(files)
```

3.
```{r}
?rbindlist
?lapply
tables <- lapply(files, fread)
tables
dt <- rbindlist(tables, idcol = 'filename')
dt
str(dt)
```


4.
```{r}
?separate

dt <- separate(dt, col= "filename", into = c("year", "sex"))
dt

```


## Section 5

1.
```{r}
gt <- fread("extdata/eqtl/genotype.txt")
dim(gt)

head(gt[,1:5])

growth <- fread("extdata/eqtl/growth.txt")
dim(growth)
head(growth)

```

2.
```{r}
summary(gt)
summary(growth)

str(gt)
?melt
gt_melt <- melt(gt, id.vars = "strain", variable.name = "media", value.name = "growth_rate")
gt_melt
growth_melt <- melt(growth, id.vars = "strain", variable.name = "media", value.name = "growth_rate")
growth_melt

?merge
dt <- merge(growth_melt, gt_melt, by = "strain", allow.cartesian = T)
dt

dt[,gt_melt := as.factor(gt)]
dt

```


































