---
title: "Exercise 5"
output: html_notebook
---

## Section 0

1.
```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(tidyr)
# install.packages("GGally")
library(GGally)
# install.packages("pheatmap")
library(pheatmap)
# install.packages("mclust")
library(mclust)
```

## Section 1

1.
```{r}
expr<- readRDS("extdata/cancer_data.rds") %>% as.data.table(keep.rownames = "tumor_type")
head(expr[,1:6])
expr

?ggcorr
ggcorr(expr[,-"tumor_type"])

```

2.
```{r}
?pheatmap
?as.matrix
expr[]
expr_mat <- as.matrix(expr[,-"tumor_type"])
expr_mat

row.names(expr_mat) <- expr[,tumor_type]
pheatmap(expr_mat, cluster_rows = F, cluster_cols =F)
  


```

3.
```{r}
expr
expr_melt <- melt(expr, id.vars="tumor_type")
expr_melt
expr_melt[order(-value)]


ggplot(expr, aes(FUK, UGP2))+ geom_point()

expr[tumor_type=="DOHH2", FUK :=NA]
expr[tumor_type=="DOHH2", UGP2 :=NA]

ggcorr(expr[,-"tumor_type"])

```


## Section 2

1.
```{r}
iris
str(iris)

?as.matrix
plot.data <- iris[,-5] %>% as.matrix 
pheatmap(plot.data, cluster_rows = F, cluster_cols = F, scale = "column")


```

2.
```{r}
?pheatmap


pheatmap(plot.data, show_rownames = F, scale = "column", clustering_method = "complete")


```

3.
```{r}
h_complete <- pheatmap(plot.data, show_rowsnames =F, scale ="column", clustering_method = "complete", silent=T)

?cutree
complete <- cutree(h_complete$tree_row, k =3) 

complete
```

4.
```{r}
rownames(plot.data) <- 1:nrow(plot.data)
plot.data

row.ann <- data.table(Species = iris$Species)
row.ann[,complete:= factor(complete)]

pheatmap(plot.data,annotation_row = row.ann, show_rownames = F, scale = "column", clustering_method = "complete")

```

## Section 3

1.

## Section 4

1.
```{r}
dt <- data.table(x=c(8,10,4,5,6,6,3), y = c(5,7,6,8,4,9,3), letter = c("A","B","C","D","E","X1","X2"))
dt

dt[,delta.x1:= x - dt[letter =="X1",x]]
dt[,delta.x2:= x - dt[letter =="X2",x]]
dt[,delta.y1:= y - dt[letter =="X1",y]]
dt[,delta.y2:= y - dt[letter =="X2",y]]
dt

dt[, distance.x1 := sqrt(delta.x1 **2 + delta.y1**2)]
dt[, distance.x2 := sqrt(delta.x2 **2 + delta.y2**2)]
dt

dt[,cluster := ifelse(distance.x1 <distance.x2, "X1", "X2")]
dt

new.centroids <- dt[1:5, .(mean.x = mean(x),mean.y = mean(y)), by = "cluster"]


new.centroids
```

2.
```{r}
?scale
iris
plot.data

scaled.data <- scale(plot.data)
scaled.data

?kmeans
km<- kmeans(scaled.data, 3)
km
```


3.
```{r}
table(complete, km$cluster)
```

## Section 5

1. mei zuo wan
```{r}
#install.packages("fossil")
library(fossil)

```

































