---
title: "Exercise 7"
output: html_notebook
---

## Section 0

1.
```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(tidyr)
library(dplyr)
# install.packages("patchwork")
library(patchwork)
```

2.
```{r}
genotype <- fread("./extdata/eqtl/genotype.txt")
genotype <- melt(genotype, id.vars = "strain", variable.name = "marker",
                 value.name = "genotype")
growth <- fread("./extdata/eqtl/growth.txt")
growth <- melt(growth, id.vars = "strain", variable.name = "media",
               value.name = "growth_rate")
marker <- fread("./extdata/eqtl/marker.txt")
```

## Section 1

1.
```{r}

mrk

# Plotting the growth rate difference
getMaltoseDt = function(mrk){
growth_mrk <- merge(growth, genotype[marker %in% mrk, .(strain, genotype, marker)],
                       by = 'strain', allow.cartesian = TRUE)
  growth_mrk[media == "YPMalt"]
}
# boxplot
plot_growth_one_mk <- function(mk){ ggplot(getMaltoseDt(mk), aes(genotype, growth_rate)) + geom_boxplot() +
labs(title = mk) + theme_bw(base_size = 16)
}
plot_growth_one_mk("mrk_5211")

# Function to calculate the difference of the medians of two genotypes
median_diff <- function(dt){
dt[genotype == 'Wild isolate', median(growth_rate, na.rm=T)] -
    dt[genotype == 'Lab strain', median(growth_rate, na.rm=T)]
}
# Function to permute the table, plot the resulting histogram # and compute a p-value
p_val_medians <- function(dt, N_permu = 1000){
  # It will return both a pvalue and plot a histogram of T_star
T_ref <- median_diff(dt)
T_star <- sapply(1:N_permu, function(x){
median_diff(dt[, genotype := sample(genotype)]) }) # Plot
  g <- ggplot(data = data.table(T_star = T_star), aes(T_star)) + geom_histogram() +
    geom_vline(aes(xintercept=T_ref, color="T_ref")) + xlim(-3,3)
print(g) # Needed to render plot inside function call
  # Compute and return the p value
  # First compute each tail seperately
  p_val_right <- (sum(T_star >= T_ref) + 1) / (N_permu + 1)
  p_val_left <- (sum(T_star <= T_ref) + 1) / (N_permu + 1)
    # Then combine the above to obtain the double sided p-value.
  p_val <- 2 * min(p_val_right, p_val_left)
  return(p_val)
}
# Calling the function:
p_val_medians(getMaltoseDt("mrk_5211"))
  

```
2.
```{r}
growth
genotype
getMaltoseDt("mrk_1653")
plot_growth_one_mk("mrk_1653")
p_val_medians(getMaltoseDt("mrk_1653"))

getMaltoseDt("mrk_5091")
plot_growth_one_mk("mrk_5091")
p_val_medians(getMaltoseDt("mrk_5091"))
```


## Section 2

```{r}
?spread
genotype
mks_geno <- genotype[marker %in% c("mrk_5091", "mrk_5211")] %>%
  spread(marker, genotype)
mks_geno

# Ho: Marker 5091 is not significantly associated with marker 5211
# T statistic: number of times both markers had the same genotype
# OR
# T statistic: number of times both markers had the same genotype / number of strains 

mks_geno <- genotype[marker %in% c("mrk_5091", "mrk_5211")] %>% spread(marker, genotype) %>% as.data.table

mks_geno
str(mks_geno)

# Compute the number of times both markers had the same genotype
#T_ref <- mks_geno[mrk_5091 == mrk_5211, .N] # First option
T_ref <- mks_geno[mrk_5091 == mrk_5211, .N]/nrow(mks_geno) # Second option
# permutation
N_permu <- 1000
T_star <- sapply(1:N_permu, function(x){
mks_geno[mrk_5091 == sample(mrk_5211), .N]/nrow(mks_geno)}) # other alternative
# plot distribution
ggplot(data = data.table(T_star = T_star), aes(T_star)) + geom_histogram() +
  geom_vline(aes(xintercept=T_ref, color="T_ref")) + xlim(0,1)

# compute p-value
p_val <- (sum(T_star >= T_ref) + 1) / (N_permu + 1)
p_val
```


## Section 3

1.
```{r}

growth
conditioning_dt
# Add growth in maltose (YPMalt) to the genotype data
conditioning_dt <- merge(mks_geno, growth[media == "YPMalt"], by = "strain")
a <- ggplot(conditioning_dt, aes(mrk_5211, growth_rate)) +
    geom_boxplot() +
    facet_wrap(~ mrk_5091) +
    labs(title="conditioned on marker 5091")
b <- ggplot(conditioning_dt, aes(mrk_5091, growth_rate)) +
    geom_boxplot() +
    facet_wrap(~ mrk_5211) +
    labs(title="conditioned on marker 5211")
a / b #Patchwork syntax to nicely align plots




```


## Section 4




























