---
title: "Exercise 8"
output: html_notebook
---

## Section 0

1.
```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(tidyr)
library(dplyr)
library(datasets)
```

2.
```{r}
gene <- fread("./extdata/eqtl/gene.txt")
genotype <- fread("./extdata/eqtl/genotype.txt")
genotype <- melt(genotype, id.vars = 'strain', variable.name = 'marker',
                 value.name = 'genotype')
growth <- fread("./extdata/eqtl/growth.txt")
growth <- melt(growth, id.vars = "strain", variable.name = 'media',
               value.name = 'growth_rate')
marker <- fread("./extdata/eqtl/marker.txt")
```


## Section 1

1.

## Section 2

1.
```{r}
getMaltoseDt <- function(mrk){
growth_mrk <- merge(growth, genotype[marker == mrk, .(strain, genotype)],
                       by = 'strain')
  growth_mrk[media == "YPMalt"]
}
# boxplot
plot_growth_one_mk <- function(mk){ ggplot(getMaltoseDt(mk), aes(genotype, growth_rate)) + geom_boxplot() +
labs(title = mk) + theme_bw(base_size = 16) + theme(plot.title = element_text(hjust = 0.5))
}
plot_growth_one_mk("mrk_5211")
```


## Section 3

1.
```{r}
data(iris)

?cor.test
cor_value <- cor.test(iris$Sepal.Length, iris$Sepal.Width, method = "pearson")
cor_value

ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width)) +
  geom_point() +
  geom_smooth(method=lm)

```

## Section 4























