---
title: "Exercise2"
output: html_notebook
---

## Section 00

library(data.table)
library(magrittr)


## Section 01

1.
```{r}
?fread
?file.path
users_dt <- fread(file.path("extdata/BX-Users.csv"))
books_dt <- fread(file.path("extdata/BX-Books.csv"))
ratings_dt <- fread(file.path("extdata/BX-Book-Ratings.csv"))
```

2.
```{r}
class(users_dt)
class(books_dt)
class(ratings_dt)
```

3.
```{r}
colnames(users_dt)
?sapply
?`:=`
users_dt
str(users_dt)
sapply(users_dt, class)
users_dt[,Age := as.numeric(Age)]
users_dt
```
4.
```{r}
summary(books_dt)
```

5.
```{r}
?first
?head
first(ratings_dt,5)
last(ratings_dt,5)
```

6.
```{r}
?gsub
colnames(users_dt) <- gsub("-","_", colnames(users_dt))
colnames(books_dt) <- gsub("-","_", colnames(books_dt))
colnames(ratings_dt) <- gsub("-","_", colnames(ratings_dt))

```


7.
```{r}
str(books_dt)
books_dt <- books_dt[,c("ISBN","Book_Title","Book_Author","Year_Of_Publication","Publisher")]
```

8.
```{r}
books_dt_2 <- books_dt[1900<=Year_Of_Publication & Year_Of_Publication>= 2019,]
str(books_dt_2)
```

## Section 2

1.
```{r}
??unqiue
books_dt[,length(unique(Book_Author))]
```

2.
```{r}
str(books_dt)
books_dt[Year_Of_Publication >= 2000 & Year_Of_Publication <= 2010, uniqueN(Book_Author), by = Year_Of_Publication]
```
3.
```{r}
?is.na
users_dt[,sum(is.na(Age))]
users_dt[is.na(Age),.N]
```

4.
```{r}
str(ratings_dt)
ratings_dt[,max(Book_Rating)]
```

5.
```{r}
?.N
?median
ratings_dt[Book_Rating>0,.N, by = Book_Rating][N == max(N)]
```

6.
```{r}
str(ratings_dt)
ratings_dt[Book_Rating == max(Book_Rating),.N, by = ISBN][N==max(N)]
```

7.
```{r}
?order
order(-ratings_dt$Book_Rating)
ratings_dt <- ratings_dt[order(-Book_Rating)]
```

## Section 3

1.
```{r}
?ifelse
ratings_dt[,High_Rating := ifelse(Book_Rating>=7,1,0)]
```

2.
```{r}
sum(ratings_dt$High_Rating)
ratings_dt[High_Rating==1,.N]/ratings_dt[,.N]
ratings_dt[,sum(High_Rating)/.N]

```

3.
```{r}
?`%in%`
str(users_dt)
str(ratings_dt)
ratings_dt[,User_ID]
users_dt[!(User_ID %in% ratings_dt$User_ID)]
```

4.
```{r}
?remove
str(users_dt)
users_dt[User_ID %in% ratings_dt$User_ID & !is.na(Age), .N, by=Age][N== max(N)]
```

5.
```{r}
str(users_dt)
str(ratings_dt)
ratings_dt[,.N, by = User_ID][,mean(N)]
```

6.
```{r}
?order
str(ratings_dt)
ratings_dt[order(-ratings_dt$Book_Rating, Year_Of_Publication),.(Book_Title, Year_Of_Publication, Book_Rating)] %>% head(1)
```

7.
```{r}
str(ratings_dt)
ratings_dt[,Rating_Count := .N, by = ISBN]
ratings_dt[Rating_Count == max(Rating_Count), max(Year_Of_Publication)]
```

8.
```{r}
str(ratings_dt)
ratings_dt[,Max_Book_Ranking := max(Book_Rating),by = ISBN]
ratings_dt
```

9.
```{r}
str(ratings_dt)
ratings_dt_test <- ratings_dt[Book_Author %in% c("Agatha Christie","William Shakespeare")]
```

10.
```{r}
str(ratings_dt_test)
??`.()`
a <- ratings_dt_test[,c(mean(Book_Rating), max(Book_Rating)), by = Book_Author]
a
class(a)
str(a)
```


## Section 4

1.
```{r}
install.packages("readxl")
library(readxl)

data <- read_excel("extdata/summer_olympic_medals.xlsx")
str(data)
data <- as.data.table(data)

str(data)
data
data[Medal == "Bronze",.N,by=Athlete][N == max(N)]

```


2.
```{r}
str(data)
data[,unique(Gender)]
data[,unique(Event_gender)]

table(data$Gender)

data[Gender =="Men" & (Event_gender != "M" & Event_gender != "X")]

```

3.
```{r}
?read_excel
str(data)
data[,.N,by = NOC][N==max(N)][,NOC]
```

4.
```{r}
?make.names
?setdiff
```

















































